(defun test ()
  (sdl2:with-init (:everything)
    (sdl2:with-window (window)
      (sdl2:with-renderer (renderer window :flags '(:accelerated))
	(sdl2:with-event-loop (:method :poll)
	  (:keyup (:keysym keysym)
		  (let ((scancode-value (sdl2:scancode-value keysym)))
		    (cond
		      ((sdl2:scancode= scancode-value :scancode-escape) (sdl2:push-event :quit)))))
	  (:idle ()
		 (sdl2:set-render-draw-color renderer 0 0 0 255)
		 (sdl2:render-clear renderer)
		 (sdl2:render-present renderer)
		 ())
	  (:quit ()
		 t))))))
